### ISSUE TITLE
Option to disable language-specific letters transformation

### ISSUE THREAD

**Issue by EwaSniegowskaPCSS** [NatLibFi/Skosify#96]
Hi! Skosify transforms labels like `"Żywy"` into `"\u017Bywy"`.
Is there an option in skosify that turns it off
(I haven't found it in `skosify -h` listing)?
Maybe I can reconfigure some underlying library to prevent this?

This behaviour is useful, but not necessary for the software I use
(SKOSMOS and iQvoc) and it makes analysing diffs of data
before and after transformation impossible.

**Comment by osma** [comment]
Hi @EwaSniegowskaPCSS , I think this is not done directly by Skosify but the underlying RDF processing library rdflib. It also might depend on the serialization format. There is no option in Skosify to control this, as you noted. I'm not sure if rdflib even allows this to be easily controlled.

Can you check if the same happens if you only use rdflib? There is an utility called `rdfpipe` included in the rdflib distribution that simply parses and serializes RDF files. You could see what it does to one of your files.

**Comment by EwaSniegowskaPCSS** [comment]
Thank you for the quick answer and for the tips about rdflib.  I verified that `rdfpipe` does encode characters, but only when outputing NTriples (it might be required by the format, I don't know).

I also found out that when I transform encoded NTriples into TTL the charactes get decoded again. So I can use this property or just use `skosify` to produce TTL and then transform data into NTriples with a different tool, for example `riot`.
Thank you very much for your help.
